### ISSUE TITLE
Django 3.2 compatibility

### ISSUE THREAD

**Issue by philip238** [wemake-services/django-test-migrations#197]
I know Django 3.2 is not officially supported, but I'm getting the following error importing `MigratorTestCase` with Django `3.2.0`.
I'm on MacOS `10.15.6`.

```
>>> env/bin/python
Python 3.7.0 (default, Oct  8 2020, 10:13:01)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
>>> from django_test_migrations.contrib.unittest_case import MigratorTestCase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[repo_root]/env/lib/python3.7/site-packages/django_test_migrations/contrib/unittest_case.py", line 7, in <module>
    from django_test_migrations.migrator import Migrator
  File "[repo_root]/env/lib/python3.7/site-packages/django_test_migrations/migrator.py", line 9, in <module>
    from django_test_migrations import sql
  File "[repo_root]/env/lib/python3.7/site-packages/django_test_migrations/sql.py", line 5, in <module>
    from django.db import DefaultConnectionProxy, connections, transaction
ImportError: cannot import name 'DefaultConnectionProxy' from 'django.db' ([repo_root]/env/lib/python3.7/site-packages/django/db/__init__.py)
```
I've removed the absolute path for brevity.

The same error occurs on Django `3.2.1`.
This works correctly with Django `3.1.9`.

Is there any chance of this package being updated for compatibility with Django 3.2?

Thanks in advance for any help.

**Comment by philip238** [comment]
Sorry, I was on version `1.0.0`. Upgrading to `1.1.0` fixed this. 🤦
